name: XpBottle
main: org.neast.xpbottle.XpBottle
version: 1.0
api-version: 1.19
author: Neast
website: https://www.spigotmc.org/resources/xpbottle-full-config.117444/
description: >
  Un plugin pour convertir l'expérience en bouteilles d'expérience. Pour plus d'informations, visitez [le site Web du plugin](https://example.com/xpbottle).
commands:
  xpbottle:
    description: Convert your XP to bottles
    usage: /xpbottle [reload]
    permission: xpbottle.use
    permission-message: Vous n'avez pas la permission d'utiliser cette commande. Pour obtenir de l'aide, visitez [notre support en ligne](https://example.com/support).
permissions:
  xpbottle.use:
    description: Allows the player to use the /xpbottle command
    default: true
  xpbottle.reload:
    description: Allows the player to reload the plugin configuration
    default: op
  xpbottle.nocooldown:
    description: Allows the player to bypass the cooldown
    default: op
  xpbottle.vip:
    description: VIP permission with reduced cooldown
    default: false
  xpbottle.vipplus:
    description: VIP+ permission with further reduced cooldown
    default: false
