name: XpBottle
version: 1.2
author: Neast
website: https://www.spigotmc.org/resources/xpbottle-%E2%9C%A8-itemsadder-%E2%AD%90-optimize-xp-management-with-enhanced-item-integration.117444/
main: org.neast.bottlexp.Bottlexp
api-version: 1.19

commands:
  xpbottle:
    description: Convertit votre XP en papier enchanté.
    usage: /xpbottle
    permission: bottlexp.use
  xpbottle reload:
    description: Recharge la configuration de BottleXP.
    usage: /xpbottle reload
    permission: bottlexp.reload

permissions:
  bottlexp.reload:
    description: Permet de recharger la configuration de BottleXP.
    default: op
  bottlexp.use:
    description: Permet aux joueurs de convertir leur XP en papier enchanté.
    default: true
